# Generated by Django 2.2.4 on 2019-10-09 20:34

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_math_group', to='otree.Session')),
            ],
            options={
                'db_table': 'complex_math_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex_math_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'complex_math_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('task_timer', otree.db.models.PositiveIntegerField(null=True)),
                ('name', otree.db.models.StringField(max_length=10000, null=True)),
                ('nametag', otree.db.models.StringField(max_length=10000, null=True)),
                ('sentNames', otree.db.models.StringField(max_length=10000, null=True)),
                ('int1', otree.db.models.PositiveIntegerField(null=True)),
                ('int2', otree.db.models.PositiveIntegerField(null=True)),
                ('solution', otree.db.models.PositiveIntegerField(null=True)),
                ('user_total', otree.db.models.PositiveIntegerField(null=True)),
                ('task1payoff_score', otree.db.models.FloatField(null=True)),
                ('task2payoff_score', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex_math.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_math_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_math_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex_math.Subsession')),
            ],
            options={
                'db_table': 'complex_math_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex_math.Subsession'),
        ),
    ]
